# Stubs for matchpy.matching (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .many_to_one import *
from .bipartite import *
from .one_to_one import *
from .syntactic import *
