# Stubs for matchpy.matching.one_to_one (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..expressions.expressions import Expression, Pattern
from ..expressions.substitution import Substitution
from typing import Iterator, Tuple

def match(subject: Expression, pattern: Pattern) -> Iterator[Substitution]: ...
def match_anywhere(subject: Expression, pattern: Pattern) -> Iterator[Tuple[Substitution, Tuple[int, ...]]]: ...
