# Stubs for matchpy.expressions (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .expressions import *
from .substitution import *
from .constraints import *
from .functions import *


# Names in __all__ with no definition:
#   Arity
#   AssociativeOperation
#   Atom
#   CommutativeOperation
#   Constraint
#   CustomConstraint
#   EqualVariablesConstraint
#   Expression
#   OneIdentityOperation
#   Operation
#   Pattern
#   Substitution
#   Symbol
#   SymbolWildcard
#   Wildcard
#   contains_variables_from_set
#   create_operation_expression
#   get_head
#   get_variables
#   is_anonymous
#   is_constant
#   is_syntactic
#   make_dot_variable
#   make_plus_variable
#   make_star_variable
#   make_symbol_variable
#   match_head
#   op_iter
#   op_len
#   preorder_iter
#   preorder_iter_with_position
#   register_operation_factory
#   register_operation_iterator
#   rename_variables
