# Stubs for matchpy (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .expressions import * # type: ignore
from .functions import *
from .utils import *
from .matching import *
# Names in __all__ with no definition:
#   Arity
#   AssociativeOperation
#   Atom
#   BipartiteGraph
#   CommutativeOperation
#   Constraint
#   CustomConstraint
#   DiscriminationNet
#   EqualVariablesConstraint
#   Expression
#   FlatTerm
#   ManyToOneMatcher
#   ManyToOneReplacer
#   OneIdentityOperation
#   Operation
#   Pattern
#   SequenceMatcher
#   Substitution
#   Symbol
#   SymbolWildcard
#   Wildcard
#   base_solution_linear
#   cached_property
#   commutative_sequence_variable_partition_iter
#   contains_variables_from_set
#   create_operation_expression
#   enum_maximum_matchings_iter
#   extended_euclid
#   fixed_integer_vector_iter
#   generator_chain
#   get_head
#   get_short_lambda_source
#   get_variables
#   is_anonymous
#   is_constant
#   is_match
#   is_operation
#   is_symbol_wildcard
#   is_syntactic
#   make_dot_variable
#   make_plus_variable
#   make_star_variable
#   make_symbol_variable
#   match
#   match_anywhere
#   match_head
#   op_iter
#   op_len
#   preorder_iter
#   preorder_iter_with_position
#   register_operation_factory
#   register_operation_iterator
#   rename_variables
#   replace_many
#   slot_cached_property
#   solve_linear_diop
#   substitute
#   weak_composition_iter
