# Stubs for matchpy.matching (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .many_to_one import ManyToOneMatcher, ManyToOneReplacer
from .bipartite import BipartiteGraph, enum_maximum_matchings_iter
from .one_to_one import match, match_anywhere
from .syntactic import FlatTerm, is_operation, is_symbol_wildcard, DiscriminationNet, SequenceMatcher
